config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
  devise_for :users
  resources :events do
  	resources :tickets
  end
  root "events#index"
  end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :tickets
	validates :title, presence: true, length: { minimum: 5}
	validates :details, presence: true
	validates :conducted_on, presence: true
	validates :ticket_charge, presence: true
	validates :total_tickets, presence: true
	validates :event_sub, presence: true
	validates :no_of_days, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  validates :name, presence: true
	validates :gender, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
   before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
        # Fields for sign up
        devise_parameter_sanitizer.for(:sign_up)  { |u| u.permit( :email, :password, :current_password, :gender, :name,)}
        # Fields for editing an existing account
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :gender, :name )}
    end

    $tickets =1
     $count =5


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@events = Event.all.order('created_at DESC')


	end

	 def new

	 end

	 def create
		@event = Event.new(event_params)
		@event.save
		redirect_to @event, notice: "Successfully create new event"

		
	end

	def show
		@event = Event.find(params[:id])
		$tickets = @event.total_tickets.to_i - @event.tickets.count.to_i	  
		
        $count = @event.ticket_charge.to_f-(Float(@event.ticket_charge.to_f * 5.00) / 100.00).to_f


	end

	private
	def event_params
		params.require(:event).permit(:title, :details, :conducted_on, :ticket_charge, :total_tickets, :event_sub, :no_of_days)
	end


   

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	def create
		@event = Event.find(params[:event_id])
		@q = @event
		@ticket = @event.tickets.create(params[:ticket].permit(:participant, :gender, :user, :fee))		
        @event.save   

		redirect_to event_path(@event)
	end
	def destroy
		@event = Event.find(params[:event_id])
		@ticket = @event.tickets.find(params[:id])
		@ticket.destroy

		redirect_to event_path(@event)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/index.html.erb
 <% @events.each do |event| %>
<div class="event_wrapper">
	<% if event.conducted_on >= Time.now %>
	<ul class="nav pull-right">
	<h2 class="event_sub">Fee Rs. <%= event.ticket_charge.to_d	 %></h2>
	</ul>
	<h2 class="title"><%= link_to event.title, event %></h2>
	
	<p class="event_sub"> <%= event.event_sub %></p>
	<p class="date"><%= event.created_at.strftime("%B %d, %Y") %></p>
	<hr>
	<% end %>
</div>
<% end %>

app/views/events/new.html.erb
<div id="page_wrapper">
	<h1>New Events</h1>

	<%= form_for :event, url: events_path do |f| %> 
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :event_sub %><br>
		<%= f.text_field :event_sub %>
	</p>


	<p>
		<%= f.label :conducted_on %><br>
		<%= f.date_field :conducted_on %>
	</p>

	<p>
		<%= f.label :no_of_days %><br>
		<%= f.text_field :no_of_days %>
	</p>

	<p>
		<%= f.label :ticket_charge %><br>
		<%= f.text_field :ticket_charge %>
	</p>

	<p>
		<%= f.label :total_tickets %><br>
		<%= f.text_field :total_tickets %>
	</p>

	<p>
		<%= f.label :details %><br>
		<%= f.text_area :details %>
	</p>

	<p>
		<%= f.submit %>
	</p>

	<% end %>

</div>

app/views/events/show.html.erb
<% if user_signed_in? %>
	<% @t = User.find(current_user) -%>
	<ul class="nav pull-right">
		<% if(@t.gender == "female") %>
			<h1 class="ticket_charge">
				Rs. <%= number_with_precision($count, :precision => 2)%><br>					
		 	</h1>
		 	5% discounted 
	 	<% else %>
	   		<h1 class="ticket_charge">
	   			<% $count = @event.ticket_charge %>
				Rs. <%= number_with_precision($count , :precision => 2)%>
			</h1>
	   	<% end %>
	</ul>
<% else %>
	<ul class="nav pull-right">
		<h1 class="ticket_charge">
			<% $count = @event.ticket_charge %>
			Rs. <%= number_with_precision($count, :precision => 2)%><br>			
		</h1>
		5% discount in ticket price for women
	</ul>

<% end %>
	


<h1 class="title">
	<%= @event.title %> 
 </h1>
 

<p class="date">
	Submitted <%= time_ago_in_words(@event.created_at) %> Ago
</p>

<h4 class="conducted_on">
 	on <%= @event.conducted_on %> 
 	<% if @event.no_of_days == 1 %>
 	 ( <%= @event.no_of_days %> day ) 
 	 <% else %>
 	  ( <%= @event.no_of_days %> days ) 
 	   <% end %>
 </h4>

<ul class="nav pull-right">
	<h4 class="tickets">
	<%= $tickets %> Tickets left
 </h4>
</ul><br>

 <p class="event_sub">
 	sub: <%= @event.event_sub %>
 </p>


<p class="details">
	<%= @event.details %>
</p>
<hr>



<div id="tickets">
<h4><%= @event.tickets.count %> Attends</h4><br>
<br><%= render @event.tickets %>
</div>

<% if user_signed_in? %>
<% if(@tickets == 0) %>
<h3>Ticked Completed</h3>
<% else %>
 		<br><%= render "tickets/form" %>
<% end %>

<% else %>
<%= link_to "Please Log In or Register for Attending This Event", new_user_registration_path %><br><br>
<% end %>


</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar navbar-inverse">
	<div class="navbar-inner">
		<div class="container">			
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#">Events</a>
				<ul class="nav pull-right">
					 <% if user_signed_in? %>
					 <% @t = User.find(current_user) -%>
					<li><%= link_to "Home", root_path %></li>		
			  		
					<li><%= link_to "Log Out("+@t.name+")", destroy_user_session_path, method: :delete %></li>  
					<% else %>
					<li><%= link_to "Home", root_path %></li>			
			  		<li><%= link_to "Register", new_user_registration_path %></li>
					<li><%= link_to "Log In", new_user_session_path %></li>  
					<% end %>

				</ul>
			</div>
		</div>
	</div>
</div><br><br>




<br><div class="container">
	<div class="row">
		<% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>"><%= msg %></div>
        <% end %>
  	<%= yield %>
  	<div class="span3">
  		
  	</div>
  </div>
  </div>


</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for([@event, @event.tickets.build]) do |f| %>
<% @t = User.find(current_user) -%>
<p>
	<%= f.hidden_field :participant, :value => @t.name%>
</p>
<p>
	<%= f.hidden_field :gender, :value => @t.gender%>
</p>
<p>
	<%= f.hidden_field :user, :value => @t.id %>
</p>
<p>
	<%= f.hidden_field :fee, :value => $count %>
</p>
<br>
<p>
	<%= f.submit "Attend" %>
</p>
<% end %>

app/views/tickets/_ticket.html.erb
<div class="ticket clearfix">
	<div class="ticket_content">
		<p class="ticket_name"><strong><%= ticket.participant %></strong></p>
		 <% if user_signed_in? %>
		<ul class="nav pull-right">
		<p><%= link_to 'Unattend', [ticket.event, ticket],
					method: :delete,
					class: "button",
						data: { confirm: 'Are you sure?' } %>
		</p>
		</ul>
		<% end %>
		<p class="ticket_body"><%= ticket.gender %></p>
		<p class="ticket_time"><%= time_ago_in_words(ticket.created_at) %> Ago</p>
		
	</div>

	<hr>
</div>